# Site settings
email: studio@xxix.co
description: > # this means to ignore newlines until "baseurl:"
  The base template for creating awesome documentation for XXIX clients. You'll want to fill this space with a short description and reminder of the site URL.
baseurl: "" # the subpath of your site, e.g. /blog/
client: "Client Name"

# Build settings
markdown: kramdown
